/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.ArbitrosDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Arbitro;

/**
 *
 * @author desarrollo
 */
public class ArbitrosVista extends FormBase {

    private static final long serialVersionUID = -3409152840623538558L;

    private final ArbitrosDAO arbitrosDAO;
    private Arbitro arbitro;
    /**
     * Creates new form ArbitrosVista
     * @param con
     */
    public ArbitrosVista(Connection con) {
        initComponents();
        arbitrosDAO = new ArbitrosDAO(con);
        lblEditando.setVisible(false);
        List<Arbitro> lista = arbitrosDAO.consultaArbitros(null);
        if (lista != null && !lista.isEmpty()) {
            for (Arbitro a : lista) {
                ((DefaultTableModel) tblArbitros.getModel()).addRow(new Object[] {a.getIdArbitro(), a.getNombre()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblEditando = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArbitros = new javax.swing.JTable();

        setClosable(true);
        setTitle("Registro/Consulta Arbitros");

        jLabel1.setText("Nombre:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        lblEditando.setForeground(java.awt.Color.red);
        lblEditando.setText("Editando...");

        tblArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArbitros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarArbitro(evt);
            }
        });
        jScrollPane1.setViewportView(tblArbitros);
        if (tblArbitros.getColumnModel().getColumnCount() > 0) {
            tblArbitros.getColumnModel().getColumn(0).setResizable(false);
            tblArbitros.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblArbitros.getColumnModel().getColumn(1).setResizable(false);
            tblArbitros.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBuscar)
                    .addComponent(btnGuardar)
                    .addComponent(lblEditando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        limpiarTabla(tblArbitros);
        txtNombre.setText("");
        lblEditando.setVisible(false);
    }//GEN-LAST:event_limpiar

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        limpiarTabla(tblArbitros);
        lblEditando.setVisible(false);
        arbitro = null;
        List<Arbitro> lista = arbitrosDAO.consultaArbitros(txtNombre.getText());
        if (lista == null || lista.isEmpty()) {
            agregarMensajeAdvertencia("No se encontraron resultados");
            return;
        }
        for (Arbitro a : lista) {
            ((DefaultTableModel) tblArbitros.getModel()).addRow(new Object[]{a.getIdArbitro(), a.getNombre()});
        }
    }//GEN-LAST:event_buscar

    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        int dialogResult = JOptionPane.showConfirmDialog(null, "Desea guardar los datos del arbitro?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (txtNombre.getText() == null || txtNombre.getText().isEmpty()) {
                agregarMensajeAdvertencia("El nombre es requerido");
                return;
            }
            if (arbitro == null) {
                arbitro = new Arbitro();
            }
            arbitro.setNombre(txtNombre.getText());
            try {
                arbitrosDAO.guardar(arbitro);
                if (arbitro.getIdArbitro() != null && arbitro.getIdArbitro() > 0) {
                    agregarMensajeExito("El registro fue actualizado correctamente");
                } else {
                    agregarMensajeExito("El registro fue guardado correctamente");
                }
                txtNombre.setText("");
                lblEditando.setVisible(false);
                arbitro = null;
                buscar(null);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_guardar

    private void seleccionarArbitro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarArbitro
        if (SwingUtilities.isRightMouseButton(evt)) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea editar el detalle del arbitro?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                arbitro = new Arbitro((Integer) tblArbitros.getValueAt(tblArbitros.getSelectedRow(), 0),
                                                (String) tblArbitros.getValueAt(tblArbitros.getSelectedRow(), 1), true);
                txtNombre.setText(arbitro.getNombre());
                lblEditando.setVisible(true);
            }
        }
    }//GEN-LAST:event_seleccionarArbitro


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditando;
    private javax.swing.JTable tblArbitros;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
