/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.JugadoresDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Equipos;
import lmfvgo.modelo.Jugadores;

/**
 *
 * @author cgarcia
 */
public class EquipoAltaJugadoresVista extends FormBase {

    private final EquiposDAO equiposDAO;
    private final JugadoresDAO jugadoresDAO;

    /**
     * Creates new form EquipoAltaJugadoresVista
     */
    public EquipoAltaJugadoresVista() {
        initComponents();
        equiposDAO = new EquiposDAO();
        jugadoresDAO = new JugadoresDAO();

        inicializarJugadores();
        List<Equipos> equipos = equiposDAO.consultarEquipo(null, 0);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cboEquipos.getModel();
        modelo.addElement("0 - Seleccione");
        for (Equipos eq : equipos) {
            modelo.addElement(eq.getIdEquipo() + " - " + eq.getNombre());
        }
    }

    private void inicializarJugadores() {
        lstJugEq.setModel(new DefaultListModel());
        List<String> jugadores = jugadoresDAO.consultaJugadoresLibre();
        DefaultListModel model = new DefaultListModel();
        model.removeAllElements();
        for (String jug : jugadores) {
            model.addElement(jug);
        }
        lstJugadores.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstJugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstJugEq = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        cboEquipos = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setTitle("ALTA DE JUGADORES EN EQUIPOS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jugadores");

        lstJugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstJugadores);

        lstJugEq.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstJugEq);

        jLabel2.setText("Equipo");

        cboEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarJugadores(evt);
            }
        });

        btnAgregar.setLabel("Agregar >>");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar(evt);
            }
        });

        btnQuitar.setLabel("<< Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitar(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 289, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitar)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar
        if (cboEquipos.getSelectedIndex() > 0) {
            if (lstJugadores.getSelectedValue() != null && !lstJugadores.getSelectedValue().isEmpty()) {
                String seleccionado = lstJugadores.getSelectedValue();
                ((DefaultListModel) lstJugadores.getModel()).removeElementAt(lstJugadores.getSelectedIndex());

                if (lstJugEq.getModel() == null || lstJugEq.getModel().getSize() == 0) {
                    lstJugEq.setModel(new DefaultListModel());
                }
                ((DefaultListModel) lstJugEq.getModel()).addElement(seleccionado);
            } else {
                agregarMensajeAdvertencia("Debe seleccionar un jugador");
            }
        } else {
            agregarMensajeAdvertencia("Debe seleccionar un equipo");
        }
    }//GEN-LAST:event_agregar

    private void actualizarJugadores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarJugadores
        DefaultListModel model = (DefaultListModel) lstJugEq.getModel();
        model.removeAllElements();
        Jugadores filtro = new Jugadores();
        filtro.setEquipo(Integer.parseInt(cboEquipos.getSelectedItem().toString().split(" - ")[0].trim()));
        if (filtro.getEquipo() > 0) {
            List<Jugadores> jgs = jugadoresDAO.consultarJugadores(filtro);
            if (jgs != null && !jgs.isEmpty()) {
                for (Jugadores j : jgs) {
                    model.addElement(j.getIdJugador() + " - " + j.getNombre() + " " + j.getPaterno() + " " + j.getMaterno());
                }
                lstJugEq.setModel(model);
            }
        }
    }//GEN-LAST:event_actualizarJugadores

    private void quitar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitar
        if (lstJugEq.getSelectedValue() != null && !lstJugEq.getSelectedValue().isEmpty()) {
            String seleccionado = lstJugEq.getSelectedValue();
            ((DefaultListModel) lstJugEq.getModel()).removeElementAt(lstJugEq.getSelectedIndex());

            if (lstJugadores.getModel() == null || lstJugadores.getModel().getSize() == 0) {
                lstJugadores.setModel(new DefaultListModel());
            }
            ((DefaultListModel) lstJugadores.getModel()).addElement(seleccionado);
        } else {
            agregarMensajeAdvertencia("Debe seleccionar un jugador");
        }
    }//GEN-LAST:event_quitar

    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        DefaultListModel dlm = (DefaultListModel) lstJugEq.getModel();
        if (dlm.getSize() > 0) {
            String eqSel = cboEquipos.getSelectedItem().toString().split(" - ")[0];
            Integer idEquipo = Integer.parseInt(eqSel.trim());
            List<Integer> idsJugs = new ArrayList<>();
            for (int i = 0; i < dlm.getSize(); i++) {
                idsJugs.add(Integer.parseInt(dlm.getElementAt(i).toString().split(" - ")[0]));
            }
            try {
                equiposDAO.limpiarEquipo(idEquipo);
                equiposDAO.guardarJugadoresEquipo(idEquipo, idsJugs);
                agregarMensajeExito("Se guardaron los registros correctamente");
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }

        } else {
            agregarMensajeAdvertencia("No se han agregado jugadores al equipo");
        }
    }//GEN-LAST:event_guardar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cboEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstJugEq;
    private javax.swing.JList<String> lstJugadores;
    // End of variables declaration//GEN-END:variables
}
