/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.JugadoresDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Equipos;
import lmfvgo.reportes.vo.CedulaVO;
import lmfvgo.util.ReportesManager;

/**
 *
 * @author sandra
 */
public class EquipoRegistroVista extends FormBase {

    private static final long serialVersionUID = -2371466490914252211L;
    
    private final EquiposDAO equiposDAO;
    private final JugadoresDAO jugadoresDAO;
    private final Map<String, Integer> catFuerza;
    private Integer equipoSeleccionado;
    private final ReportesManager reportesManager;

    /**
     * Creates new form EquipoRegistroVista
     * @param con
     */
    public EquipoRegistroVista(Connection con) {
        initComponents();
        lblActualizando.setVisible(false);
        btnEliminar.setVisible(false);
        btnCedula.setVisible(false);
        equiposDAO = new EquiposDAO(con);
        jugadoresDAO = new JugadoresDAO(con);
        reportesManager = new ReportesManager(con);
        catFuerza = new HashMap<>();
        catFuerza.put("SELECCIONE", 0);
        catFuerza.put("PRIMERA", 1);
        catFuerza.put("SEGUNDA", 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboFuerza = new javax.swing.JComboBox<String>();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblActualizando = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCedula = new javax.swing.JButton();

        setClosable(true);
        setTitle("REGISTRO DE EQUIPOS");

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("FUERZA:");

        cboFuerza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "PRIMERA", "SEGUNDA" }));
        cboFuerza.setPreferredSize(new java.awt.Dimension(100, 20));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        lblActualizando.setForeground(new java.awt.Color(255, 0, 0));
        lblActualizando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizando.setText("ACTUALIZANDO...");

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "FUERZA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarEquipo(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblResultado.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblResultado.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        btnEliminar.setText("Baja");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaEquipo(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar(evt);
            }
        });

        btnCedula.setText("Cédula");
        btnCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarCedula(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblActualizando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboFuerza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBuscar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActualizando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        txtNombre.setText("");
        cboFuerza.setSelectedIndex(0);
        limpiarTabla(tblResultado);
        lblActualizando.setVisible(false);
        btnEliminar.setVisible(false);
        btnCedula.setVisible(false);
        equipoSeleccionado = null;
    }//GEN-LAST:event_limpiar

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        limpiarTabla(tblResultado);
        List<Equipos> resultado = equiposDAO.consultarEquipo(txtNombre.getText(), catFuerza.get(cboFuerza.getSelectedItem().toString()));
        if (resultado != null && !resultado.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) tblResultado.getModel();
            for (Equipos eq : resultado) {
                model.addRow(new Object[]{eq.getIdEquipo(), eq.getNombre(), getFuerza(eq.getFuerza())} );
            }
        } else {
            agregarMensajeAdvertencia("No se encontraron resultados");
        }
    }//GEN-LAST:event_buscar

    private String getFuerza(int fuerza) {
        for (String key : catFuerza.keySet()) {
            if (catFuerza.get(key).equals(fuerza)) {
                return key;
            }
        }
        return "";
    }
    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        if (txtNombre.getText() == null || txtNombre.getText().isEmpty()) {
            agregarMensajeAdvertencia("El nombre es requerido.");
            return;
        }
        if (cboFuerza.getSelectedIndex() == 0) {
            agregarMensajeAdvertencia("La fuerza es requerida.");
            return;
        }
        Equipos eq = new Equipos(equipoSeleccionado != null && equipoSeleccionado > 0 ? equipoSeleccionado : null, 
                txtNombre.getText().trim(), cboFuerza.getSelectedIndex(), new Date());
        try {
            equiposDAO.guardarEquipo(eq);
            agregarMensajeExito("El registro fue guardado correctamente");
            limpiar(evt);
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_guardar

    private void editarEquipo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarEquipo
        if (SwingUtilities.isRightMouseButton(evt)) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea editar el registro?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                DefaultTableModel modelo = (DefaultTableModel) tblResultado.getModel();
                equipoSeleccionado = (Integer) modelo.getValueAt(tblResultado.getSelectedRow(), 0);
                txtNombre.setText((String) modelo.getValueAt(tblResultado.getSelectedRow(), 1));
                cboFuerza.setSelectedItem((String) modelo.getValueAt(tblResultado.getSelectedRow(), 2));
                lblActualizando.setVisible(true);
                btnEliminar.setVisible(true);
                btnCedula.setVisible(true);
            }
        }
    }//GEN-LAST:event_editarEquipo

    private void bajaEquipo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaEquipo
        String motivoBaja = JOptionPane.showInputDialog(null, "Para realizar la baja ingrese el motivo", "");
        if (motivoBaja == null) {
            return;
        }
        if (motivoBaja.trim().isEmpty()) {
            agregarMensajeAdvertencia("Debe ingresar un motivo de baja");
            return;
        }
        try {
            equiposDAO.bajaEquipo(equipoSeleccionado, motivoBaja);
            agregarMensajeExito("El equipo fue dado de baja correctamente");
            limpiar(evt);
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_bajaEquipo

    private void cerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar
        this.dispose();
    }//GEN-LAST:event_cerrar

    private void generarCedula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarCedula
        List<CedulaVO> cedula = jugadoresDAO.consultaCedula(equipoSeleccionado);
        if (cedula == null) {
            cedula = new ArrayList<>();
        }
        try {
            reportesManager.cedulaEquipo(cedula, txtNombre.getText());
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
        
    }//GEN-LAST:event_generarCedula


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCedula;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboFuerza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualizando;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
