/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.JugadoresDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Equipos;
import lmfvgo.modelo.Jugadores;
import lmfvgo.reportes.vo.ConsultaJugadoresVO;
import lmfvgo.util.ReportesManager;

/**
 *
 * @author cgarcia
 */
public class JugadorConsultaVista extends FormBase {

    private static final long serialVersionUID = 7466806948907236876L;
    
    private final JugadoresDAO jugadoresDAO;
    private final EquiposDAO equiposDAO;
    private final ReportesManager reportesManager;
    private Connection connection;

    /**
     * Creates new form JugadorConsultaVista
     * @param con
     */
    public JugadorConsultaVista(Connection con) {
        this.connection = con;
        initComponents();
        jugadoresDAO = new JugadoresDAO(con);
        equiposDAO = new EquiposDAO(con);
        reportesManager = new ReportesManager(con);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboEquipos = new javax.swing.JComboBox<>();
        cboFuerza = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();

        setClosable(true);
        setTitle("CONSULTA DE JUGADORES");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Equipo");

        cboFuerza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Primera", "Segunda" }));
        cboFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarEquipos(evt);
            }
        });

        jLabel5.setText("Fuerza");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Nombre", "Ap. Paterno", "Ap. Materno", "Procedencia", "Equipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirDetalle(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboEquipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnExportar)
                                        .addGap(7, 7, 7)))
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExportar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        txtNombre.setText(null);
        txtPaterno.setText(null);
        txtMaterno.setText(null);
        cboEquipos.removeAllItems();
        cboFuerza.setSelectedIndex(0);
        limpiarTabla(tblResultados);
    }//GEN-LAST:event_limpiar

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        Jugadores filtros = getFiltros();
        if (filtros == null) {
            agregarMensajeAdvertencia("Se debe ingresar al menos un criterio de busqueda");
            return;
        }
        
        List<Jugadores> jugadores = jugadoresDAO.consultarJugadores(filtros, true);
        limpiar(evt);
        if (jugadores != null && !jugadores.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
            for (Jugadores j : jugadores) {
                model.addRow(new Object[]{j.getIdJugador(), j.getNombre(), j.getPaterno(), j.getMaterno(),
                j.getLugarProcedencia(), j.getEquipoNombre()});
            }
            resizeColumnWidth(tblResultados);
        } else {
            agregarMensajeError("No se encontraron resultados");
        }
    }//GEN-LAST:event_buscar

    private Jugadores getFiltros() {
        Jugadores filtros = new Jugadores();
        int idx = 0;
        if (txtNombre.getText() != null && !txtNombre.getText().trim().isEmpty()) {
            filtros.setNombre(txtNombre.getText());
            idx++;
        }
        if (txtPaterno.getText() != null && !txtPaterno.getText().trim().isEmpty()) {
            filtros.setPaterno(txtPaterno.getText());
            idx++;
        }
        if (txtMaterno.getText() != null && !txtMaterno.getText().trim().isEmpty()) {
            filtros.setMaterno(txtMaterno.getText());
            idx++;
        }
        if (cboFuerza.getSelectedIndex() > 0) {
            filtros.setFuerza(cboFuerza.getSelectedIndex());
            idx++;
        }
        if (cboEquipos.getSelectedIndex() > 0) {
            filtros.setEquipo(Integer.parseInt(cboEquipos.getSelectedItem().toString().split(" - ")[0]));
            idx++;
        }
        return idx > 0 ? filtros : null;
    }
    private void actualizarEquipos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarEquipos
        int cat = cboFuerza.getSelectedIndex();
        if (cat == 0) {
            cboEquipos.removeAllItems();
            return;
        }
        List<Equipos> equipos = equiposDAO.consultarEquipo(null, cat);
        if (equipos != null && !equipos.isEmpty()) {
            List<String> opciones = new ArrayList<>();
            opciones.add("0 - Seleccione");
            for (Equipos eq : equipos) {
                opciones.add(eq.getIdEquipo() + " - " + eq.getNombre());
            }
            cboEquipos.setModel(new DefaultComboBoxModel(opciones.toArray()));
        } else {
            cboEquipos.removeAllItems();
        }
    }//GEN-LAST:event_actualizarEquipos

    private void abrirDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirDetalle
        if (SwingUtilities.isRightMouseButton(evt)) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea abrir el detalle del jugador?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
                JugadoresRegistroVista jrv = new JugadoresRegistroVista((Integer) model.getValueAt(tblResultados.getSelectedRow(), 0), connection);
                this.getParent().add(jrv);
                jrv.show();
                this.dispose();
            }
        }
    }//GEN-LAST:event_abrirDetalle

    private void exportar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportar
        if (tblResultados.getRowCount() > 0) {
            List<ConsultaJugadoresVO> consulta = new ArrayList<>();
            for (int i = 0; i < tblResultados.getRowCount(); i++) {
                ConsultaJugadoresVO vo = new ConsultaJugadoresVO();
                vo.setFolio((int) tblResultados.getValueAt(i, 0));
                vo.setNombre((String) tblResultados.getValueAt(i, 1) + " " + (String) tblResultados.getValueAt(i, 2) + " " + (String) tblResultados.getValueAt(i, 3));
                vo.setProcedencia((String) tblResultados.getValueAt(i, 4));
                vo.setEquipo((String) tblResultados.getValueAt(i, 5));
                consulta.add(vo);
            }
            try {
                reportesManager.consultaJugadores(consulta);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_exportar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboEquipos;
    private javax.swing.JComboBox<String> cboFuerza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
