/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import javax.swing.JOptionPane;
import lmfvgo.db.TorneoDAO;
import lmfvgo.modelo.Torneo;

/**
 *
 * @author cgarcia
 */
public class LigaFutbolMain extends javax.swing.JFrame {
    private static final long serialVersionUID = -8859322752060669243L;

    private final TorneoDAO torneoDAO;
    /**
     * Creates new form LigaFutbolMain
     */
    public LigaFutbolMain() {
        initComponents();
        torneoDAO = new TorneoDAO();
        Torneo torneo = torneoDAO.torneoActivo();
        if (torneo == null) {
            JOptionPane.showMessageDialog(this, "NO EXISTE TORNEO ACTIVO", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuTorneo = new javax.swing.JMenu();
        mnuTorneoNuevo = new javax.swing.JMenuItem();
        mnuTorneoCerrar = new javax.swing.JMenuItem();
        menuEquipos = new javax.swing.JMenu();
        mnuEqRegistro = new javax.swing.JMenuItem();
        mnuEqConsulta = new javax.swing.JMenuItem();
        mnuEquipoEstadisticas = new javax.swing.JMenuItem();
        menuJugadores = new javax.swing.JMenu();
        mnuJugConsulta = new javax.swing.JMenuItem();
        mnuJugRegistro = new javax.swing.JMenuItem();
        menuJuegos = new javax.swing.JMenu();
        mnuJgosRol = new javax.swing.JMenuItem();
        mnuJgosJornada = new javax.swing.JMenuItem();
        menuCredenciales = new javax.swing.JMenu();
        mnuCredJug = new javax.swing.JMenuItem();
        mnuCredEq = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liga Municipal de Futbol de Villa González Ortega");
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        menuTorneo.setText("Torneos");

        mnuTorneoNuevo.setText("Registro/Consulta");
        mnuTorneoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTorneoNuevoActionPerformed(evt);
            }
        });
        menuTorneo.add(mnuTorneoNuevo);

        mnuTorneoCerrar.setText("Cerrar");
        mnuTorneoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCierreTorneo(evt);
            }
        });
        menuTorneo.add(mnuTorneoCerrar);

        jMenuBar1.add(menuTorneo);

        menuEquipos.setText("Equipos");

        mnuEqRegistro.setText("Registro/Consulta");
        mnuEqRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEqRegistroActionPerformed(evt);
            }
        });
        menuEquipos.add(mnuEqRegistro);

        mnuEqConsulta.setText("Alta Jugadores");
        mnuEqConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEqConsultaActionPerformed(evt);
            }
        });
        menuEquipos.add(mnuEqConsulta);

        mnuEquipoEstadisticas.setText("Estadísticas");
        mnuEquipoEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirEstadisticasEquipo(evt);
            }
        });
        menuEquipos.add(mnuEquipoEstadisticas);

        jMenuBar1.add(menuEquipos);

        menuJugadores.setText("Jugadores");

        mnuJugConsulta.setText("Consulta");
        mnuJugConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConsultaJugadores(evt);
            }
        });
        menuJugadores.add(mnuJugConsulta);

        mnuJugRegistro.setText("Registro");
        mnuJugRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorRegistro(evt);
            }
        });
        menuJugadores.add(mnuJugRegistro);

        jMenuBar1.add(menuJugadores);

        menuJuegos.setText("Juegos");
        menuJuegos.setPreferredSize(new java.awt.Dimension(55, 19));

        mnuJgosRol.setText("Rol de Juegos");
        mnuJgosRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirRolJuegos(evt);
            }
        });
        menuJuegos.add(mnuJgosRol);

        mnuJgosJornada.setText("Registro de Jornada");
        mnuJgosJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirRegistroJornada(evt);
            }
        });
        menuJuegos.add(mnuJgosJornada);

        jMenuBar1.add(menuJuegos);

        menuCredenciales.setText("Credenciales");

        mnuCredJug.setText("Por Jugador");
        mnuCredJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCredJugador(evt);
            }
        });
        menuCredenciales.add(mnuCredJug);

        mnuCredEq.setText("Por Equipo");
        mnuCredEq.setToolTipText("");
        mnuCredEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCredEquipo(evt);
            }
        });
        menuCredenciales.add(mnuCredEq);

        jMenuBar1.add(menuCredenciales);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEqRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEqRegistroActionPerformed
        EquipoRegistroVista equipos= new EquipoRegistroVista();
        this.add(equipos);
        equipos.show();
    }//GEN-LAST:event_mnuEqRegistroActionPerformed

    private void jugadorRegistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorRegistro
        JugadoresRegistroVista jugadores = new JugadoresRegistroVista();
        this.add(jugadores);
        jugadores.show();
    }//GEN-LAST:event_jugadorRegistro

    private void abrirConsultaJugadores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConsultaJugadores
        JugadorConsultaVista jcv = new JugadorConsultaVista();
        this.add(jcv);
        jcv.show();
    }//GEN-LAST:event_abrirConsultaJugadores

    private void mnuEqConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEqConsultaActionPerformed
        EquipoAltaJugadoresVista ejv = new EquipoAltaJugadoresVista();
        this.add(ejv);
        ejv.show();
    }//GEN-LAST:event_mnuEqConsultaActionPerformed

    private void mnuTorneoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTorneoNuevoActionPerformed
        TorneoRegistroVista trv = new TorneoRegistroVista();
        this.add(trv);
        trv.show();
    }//GEN-LAST:event_mnuTorneoNuevoActionPerformed

    private void abrirRolJuegos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirRolJuegos
        JuegosRolVista jrv = new JuegosRolVista();
        this.add(jrv);
        jrv.show();
    }//GEN-LAST:event_abrirRolJuegos

    private void abrirRegistroJornada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirRegistroJornada
        JuegosJornadaVista jjv = new JuegosJornadaVista();
        this.add(jjv);
        jjv.show();
    }//GEN-LAST:event_abrirRegistroJornada

    private void abrirEstadisticasEquipo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirEstadisticasEquipo
        EquipoEstadisticasVista eev = new EquipoEstadisticasVista();
        this.add(eev);
        eev.show();
    }//GEN-LAST:event_abrirEstadisticasEquipo

    private void abrirCredJugador(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCredJugador
        CredencialesJugadorVista cjv = new CredencialesJugadorVista();
        this.add(cjv);
        cjv.show();
    }//GEN-LAST:event_abrirCredJugador

    private void abrirCredEquipo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCredEquipo
        CredencialesEquipoVista cev = new CredencialesEquipoVista();
        this.add(cev);
        cev.show();
    }//GEN-LAST:event_abrirCredEquipo

    private void abrirCierreTorneo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCierreTorneo
        TorneoCierreVista tcv = new TorneoCierreVista();
        this.add(tcv);
        tcv.show();
    }//GEN-LAST:event_abrirCierreTorneo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LigaFutbolMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LigaFutbolMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LigaFutbolMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LigaFutbolMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LigaFutbolMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCredenciales;
    private javax.swing.JMenu menuEquipos;
    private javax.swing.JMenu menuJuegos;
    private javax.swing.JMenu menuJugadores;
    private javax.swing.JMenu menuTorneo;
    private javax.swing.JMenuItem mnuCredEq;
    private javax.swing.JMenuItem mnuCredJug;
    private javax.swing.JMenuItem mnuEqConsulta;
    private javax.swing.JMenuItem mnuEqRegistro;
    private javax.swing.JMenuItem mnuEquipoEstadisticas;
    private javax.swing.JMenuItem mnuJgosJornada;
    private javax.swing.JMenuItem mnuJgosRol;
    private javax.swing.JMenuItem mnuJugConsulta;
    private javax.swing.JMenuItem mnuJugRegistro;
    private javax.swing.JMenuItem mnuTorneoCerrar;
    private javax.swing.JMenuItem mnuTorneoNuevo;
    // End of variables declaration//GEN-END:variables
}
