/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lmfvgo.vista;

import java.sql.Connection;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.SancionesDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Equipos;
import lmfvgo.modelo.SancionEquipo;
import lmfvgo.util.ReportesManager;

/**
 *
 * @author cgarcia
 */
public class SancionesEquiposVista extends FormBase {

    private final Connection con;
    private final EquiposDAO equiposDAO;
    private final SancionesDAO sancionesDAO;
    private final ReportesManager reportesManager;
    
    /** Creates new form SancionesEquiposVista
     * @param con */
    public SancionesEquiposVista(Connection con) {
        this.con = con;
        initComponents();
        equiposDAO = new EquiposDAO(con);
        sancionesDAO = new SancionesDAO(con);
        reportesManager = new ReportesManager(con);
        llenarTabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboFuerza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboEquipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JSpinner();
        txtJuegos = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanciones = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();

        setClosable(true);
        setTitle("SANCIONES A EQUPOS");

        jLabel1.setText("Fuerza");

        cboFuerza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Primera", "Segunda" }));
        cboFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarEquipos(evt);
            }
        });

        jLabel2.setText("Equipo");

        jLabel3.setText("Juegos");

        jLabel4.setText("Multa");

        jLabel5.setText("Puntos");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSancion(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        tblSanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo", "Fuerza", "Juegos", "Multa", "Puntos", "Obs."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarSancion(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanciones);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarSanciones(evt);
            }
        });

        jButton3.setText("Exportar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportar(evt);
            }
        });

        jLabel6.setText("Obs:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cboFuerza, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE)
                                            .addComponent(txtJuegos, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cboEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtObservaciones)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(452, 452, 452)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar)))
                        .addGap(0, 302, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEquipos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarEquipos
        int cat = cboFuerza.getSelectedIndex();
        if (cat == 0) {
            cboEquipo.removeAllItems();
            return;
        }
        List<Equipos> equipos = equiposDAO.consultarEquipo(null, cat);
        if (equipos != null && !equipos.isEmpty()) {
            List<String> opciones = new ArrayList<>();
            opciones.add("0 - Seleccione");
            for (Equipos eq : equipos) {
                opciones.add(eq.getIdEquipo() + " - " + eq.getNombre());
            }
            cboEquipo.setModel(new DefaultComboBoxModel(opciones.toArray()));
        } else {
            cboEquipo.removeAllItems();
        }
    }//GEN-LAST:event_cargarEquipos

    private void agregarSancion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSancion
        if (cboEquipo.getSelectedIndex() == 0) {
            agregarMensajeAdvertencia("El Equipo es requerido");
            return;
        }
        int conteo = 0;
        if (((Integer) txtJuegos.getValue()) > 0) {
            conteo++;
        }
        if (((Integer) txtPuntos.getValue()) > 0) {
            conteo++;
        }
        Float multa = 0F;
        if (txtMulta.getText() != null && !txtMulta.getText().isEmpty()) {
            try {
                multa = Float.parseFloat(txtMulta.getText());
                if (multa > 0) {
                    conteo++;
                }
            } catch (NumberFormatException ex) {
                
            }
        }
        if (conteo == 0) {
            agregarMensajeAdvertencia("Debe ingresar al menos uno de los campos Juegos, Multa y/o Puntos");
            return;
        }
        if (txtObservaciones.getText() == null || txtObservaciones.getText().isEmpty()) {
            agregarMensajeAdvertencia("Las observaciones son requeridas");
            return;
        }
        if (tblSanciones.getRowCount() > 0) {
            for (int i = 0; i < tblSanciones.getRowCount(); i++) {
                if (tblSanciones.getValueAt(i, 0).toString().equals(cboEquipo.getSelectedItem().toString())) {
                    agregarMensajeAdvertencia("Ya existe una sanción para el equipo seleccionado");
                    return;
                }
            }
        }
        ((DefaultTableModel) tblSanciones.getModel()).addRow(new Object[]{
            cboEquipo.getSelectedItem().toString(),
            cboFuerza.getSelectedItem().toString(),
            txtJuegos.getValue(),
            multa,
            txtPuntos.getValue(),
            txtObservaciones.getText()
        });
        limpiarFiltro();
    }//GEN-LAST:event_agregarSancion

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        limpiarFiltro();
        limpiarTabla(tblSanciones);
        llenarTabla();
    }//GEN-LAST:event_limpiar

    private void limpiarFiltro() {
        try {
            cboFuerza.setSelectedIndex(0);
            txtMulta.setText(null);
            txtJuegos.setValue(0);
            txtPuntos.setValue(0);
            txtJuegos.commitEdit();
            txtPuntos.commitEdit();
            txtObservaciones.setText(null);
        } catch (ParseException ex) {
            
        }
    }
    private void llenarTabla() {
        List<SancionEquipo> lista = sancionesDAO.consultaSancionesEquipo(cboFuerza.getSelectedIndex());
        for (SancionEquipo se : lista) {
            ((DefaultTableModel) tblSanciones.getModel()).addRow(new Object[]{
                se.getIdEquipo() + " - " + se.getNombreEquipo(),
                se.getFuerza() == 1 ? "Primera" : "Segunda",
                se.getJuegos(),
                se.getMulta(),
                se.getPuntos(),
                se.getObservaciones()
            });
            
        }
    }
    
    private void guardarSanciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarSanciones
        try {
            List<SancionEquipo> lista = new ArrayList<>();
            if (tblSanciones.getRowCount() > 0) {
                for (int i = 0; i < tblSanciones.getRowCount(); i++) {
                    SancionEquipo se = new SancionEquipo();
                    se.setIdEquipo(Integer.parseInt(tblSanciones.getValueAt(i, 0).toString().split(" - ")[0]));
                    se.setJuegos((Integer) tblSanciones.getValueAt(i, 2));
                    se.setMulta((Float) tblSanciones.getValueAt(i, 3));
                    se.setPuntos((Integer) tblSanciones.getValueAt(i, 4));
                    se.setObservaciones((String) tblSanciones.getValueAt(i, 5));
                    lista.add(se);
                }
                sancionesDAO.guardarSanciones(lista);
                agregarMensajeExito("Las sanciones fueron guardadas correctamente");
                limpiarFiltro();
            }
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_guardarSanciones

    private void exportar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportar
        if (tblSanciones.getRowCount() == 0) {
            agregarMensajeAdvertencia("No existen sanciones para exportar");
            return;
        }
        try {
            List<SancionEquipo> sanciones = new ArrayList<>();
            for (int i = 0; i < tblSanciones.getRowCount(); i++) {
                SancionEquipo se = new SancionEquipo();
                se.setNombreEquipo(((String) tblSanciones.getValueAt(i, 0)).split(" - ")[1]);
                se.setFuerza(((String) tblSanciones.getValueAt(i, 1)).equals("Primera") ? 1 : 2);
                se.setJuegos((Integer) tblSanciones.getValueAt(i, 2));
                se.setMulta((Float) tblSanciones.getValueAt(i, 3));
                se.setPuntos((Integer) tblSanciones.getValueAt(i, 4));
                se.setObservaciones((String) tblSanciones.getValueAt(i, 5));
                sanciones.add(se);
            }
            reportesManager.sancionesEquipo(sanciones);
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_exportar

    private void quitarSancion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarSancion
        try {
            if (SwingUtilities.isRightMouseButton(evt)) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Desea quitar la sanción?", "Advertencia", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    if (tblSanciones.getSelectedRow() >= 0 && tblSanciones.getSelectedRowCount() == 1) {
                        Integer idEquipo = Integer.parseInt(String.valueOf(tblSanciones.getValueAt(tblSanciones.getSelectedRow(), 0)).split(" - ")[0]);
                        String observaciones = String.valueOf(tblSanciones.getValueAt(tblSanciones.getSelectedRow(), 5));
                        if (observaciones == null || observaciones.isEmpty()) {
                            agregarMensajeAdvertencia("Debe capturar las observaciones");
                            return;
                        }
                        sancionesDAO.quitarSancionEquipo(idEquipo, observaciones);
                        ((DefaultTableModel) tblSanciones.getModel()).removeRow(tblSanciones.getSelectedRow());
                        agregarMensajeExito("La sanción fue eliminada correctamente");
                    } else {
                        agregarMensajeAdvertencia("Debe seleccionar solamente un registro");
                    }
                }
            }
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_quitarSancion


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cboEquipo;
    private javax.swing.JComboBox<String> cboFuerza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanciones;
    private javax.swing.JSpinner txtJuegos;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JSpinner txtPuntos;
    // End of variables declaration//GEN-END:variables

}
