/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.SancionesDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Expulsado;
import lmfvgo.modelo.Sancion;
import lmfvgo.util.ReportesManager;

/**
 *
 * @author desarrollo
 */
public class SancionesConsultaVista extends FormBase {

    private static final long serialVersionUID = 8482977825586734796L;

    private final EquiposDAO equiposDAO;
    private final SancionesDAO sancionesDAO;
    private List<Expulsado> sanciones;
    private ReportesManager reportesManager;
    /**
     * Creates new form SancionesConsultaVista
     * @param con
     */
    public SancionesConsultaVista(Connection con) {
        initComponents();
        equiposDAO = new EquiposDAO(con);
        sancionesDAO = new SancionesDAO(con);
        reportesManager = new ReportesManager(con);
        btnExportar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboFuerza = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanciones = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("CONSULTA SANCIONES");
        setPreferredSize(new java.awt.Dimension(900, 416));

        jLabel1.setText("Fuerza");

        cboFuerza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Primera", "Segunda" }));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSanciones(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportar(evt);
            }
        });

        tblSanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Equipo", "Fuerza", "Clave", "Juegos", "Multa", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarSancion(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanciones);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarSanciones(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnExportar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        limpiarTabla(tblSanciones);
        btnExportar.setEnabled(false);
        sanciones = null;
    }//GEN-LAST:event_limpiar

    private void buscarSanciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSanciones
        limpiarTabla(tblSanciones);
        sanciones = sancionesDAO.consultaExpulsados(cboFuerza.getSelectedIndex());
        if (sanciones != null && !sanciones.isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) tblSanciones.getModel();
            boolean agregado = false;
            for (Expulsado s : sanciones) {
                if (s.isActivo()) {
                    modelo.addRow(new Object[]{
                        (s.getIdJugador() + " - " + s.getNombreJugador()),
                        s.getNombreEquipo(),
                        s.getFuerza() == 1 ? "Primera" : "Segunda",
                        s.getClaves(),
                        s.getJuegos(),
                        s.getMulta(),
                        s.getObservaciones()
                    });
                    agregado = true;
                }
                if (!agregado) {
                    agregarMensajeError("No se encontraron resultados");
                    return;
                }
            }
            btnExportar.setEnabled(true);
        } else {
            agregarMensajeError("No se encontraron resultados");
        }
    }//GEN-LAST:event_buscarSanciones

    private void exportar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportar
            try {
                List<Expulsado> expulsados = new ArrayList<>();
                for (int i = 0; i < tblSanciones.getRowCount(); i++) {
                    Expulsado e = new Expulsado();
                    e.setIdJugador(Integer.parseInt(tblSanciones.getValueAt(i, 0).toString().split(" - ")[0]));
                    e.setNombreJugador(tblSanciones.getValueAt(i, 0).toString().split(" - ")[1]);
                    e.setNombreEquipo((String) tblSanciones.getValueAt(i, 1));
                    e.setFuerza(((String) tblSanciones.getValueAt(i, 2)).equals("Primera") ? 1 : 2);
                    e.setClaves((String) tblSanciones.getValueAt(i, 3));
                    e.setJuegos((Integer) tblSanciones.getValueAt(i, 4));
                    e.setMulta((Float) tblSanciones.getValueAt(i, 5));
                    e.setObservaciones((String) tblSanciones.getValueAt(i, 6));
                    expulsados.add(e);
                }
                reportesManager.sanciones(expulsados);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
    }//GEN-LAST:event_exportar

    private void quitarSancion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarSancion
        if (SwingUtilities.isRightMouseButton(evt)) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea quitar la sancion?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                String clave = (String) tblSanciones.getValueAt(tblSanciones.getSelectedRow(), 0);
                String jugador = (String) tblSanciones.getValueAt(tblSanciones.getSelectedRow(), 2);
                String observaciones = (String) tblSanciones.getValueAt(tblSanciones.getSelectedRow(), 6);
                try {
                    sancionesDAO.bajaSancion(Integer.valueOf(jugador.split(" - ")[0]), clave, observaciones);
                    agregarMensajeExito("La sanción fue eliminada correctamente");
                    ((DefaultTableModel) tblSanciones.getModel()).removeRow(tblSanciones.getSelectedRow());
                } catch (LMFVGOException ex) {
                    agregarMensajeError(ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_quitarSancion

    private void actualizarSanciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarSanciones
        int dialogResult = JOptionPane.showConfirmDialog(null, "Desea actualizar las sanciones?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            List<Expulsado> expulsados = new ArrayList<>();
            for (int i = 0; i < tblSanciones.getRowCount(); i++) {
                Expulsado e = new Expulsado();
                e.setIdJugador(Integer.parseInt(tblSanciones.getValueAt(i, 0).toString().split(" - ")[0]));
                e.setClaves((String) tblSanciones.getValueAt(i, 3));
                e.setJuegos((Integer) tblSanciones.getValueAt(i, 4));
                e.setMulta((Float) tblSanciones.getValueAt(i, 5));
                e.setObservaciones((String) tblSanciones.getValueAt(i, 6));
                expulsados.add(e);
            }
            try {
                sancionesDAO.actualizarExpulsiones(expulsados);
                agregarMensajeExito("La sanciones fueron actualizadas correctamente");
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_actualizarSanciones


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboFuerza;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanciones;
    // End of variables declaration//GEN-END:variables
}
