/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.EstadisticasEquipoDAO;
import lmfvgo.db.TorneoDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Equipos;
import lmfvgo.modelo.EstadisticasJugador;
import lmfvgo.modelo.Torneo;

/**
 *
 * @author USUARIO
 */
public class TorneoCierreVista extends FormBase {
    private static final long serialVersionUID = 1083223223522493168L;
    
    private final TorneoDAO torneoDAO;
    private final EstadisticasEquipoDAO estadisticasEquipoDAO;
    private final EquiposDAO equiposDAO;
    private Torneo torneo;

    /**
     * Creates new form TorneoCierreVista
     */
    public TorneoCierreVista() {
        initComponents();
        torneoDAO = new TorneoDAO();
        equiposDAO = new EquiposDAO();
        estadisticasEquipoDAO = new EstadisticasEquipoDAO();
        
        torneo = torneoDAO.torneoActivo();
        
        txtNombre.setText(torneo.getNombre());
        
        List<EstadisticasJugador> goleo1 = estadisticasEquipoDAO.consultaGoleo(1);
        List<EstadisticasJugador> goleo2 = estadisticasEquipoDAO.consultaGoleo(2);
        
        List<Equipos> equiposPrimera = equiposDAO.consultarEquipo(null, 1);
        List<Equipos> equiposPrimera2 = new ArrayList<>(equiposPrimera);
        
        List<Equipos> equiposSegunda = equiposDAO.consultarEquipo(null, 2);
        List<Equipos> equiposSegunda2 = new ArrayList<>(equiposSegunda);
        
        llenarCombo(cboCampeonPrimera, equiposPrimera);
        llenarCombo(cboSubPrimera, equiposPrimera2);
        llenarCombo(cboCampeonSegunda, equiposSegunda);
        llenarCombo(cboSubSegunda, equiposSegunda2);
        
        if (goleo1 != null && !goleo1.isEmpty()) {
            txtGoleoPrimera.setText(goleo1.get(0).getNombreJugador());
            torneo.setGoleadorPrimera(goleo1.get(0).getIdJugador());
        }
        if (goleo2 != null && !goleo2.isEmpty()) {
            txtGoleoSegunda.setText(goleo2.get(0).getNombreJugador());
            torneo.setGoleadorSegunda(goleo2.get(0).getIdJugador());
        }
    }
    
    private void llenarCombo(JComboBox combo, List<Equipos> equipos) {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) combo.getModel();
        modelo.addElement("0 - Seleccione");
        for (Equipos eq : equipos) {
            modelo.addElement(eq.getIdEquipo() + " - " + eq.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboCampeonPrimera = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cboSubPrimera = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cboCampeonSegunda = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cboSubSegunda = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtGoleoPrimera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGoleoSegunda = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nombre:");

        txtNombre.setEditable(false);

        jLabel2.setText("Fecha Fin:");

        jLabel3.setText("Campeón Primera:");

        jLabel4.setText("Subcampeón Primera:");

        jLabel5.setText("Campeón Segunda:");

        jLabel6.setText("Subcampeón Segunda:");

        jLabel7.setText("Goleo Primera:");

        txtGoleoPrimera.setEditable(false);

        jLabel8.setText("Goleo Segunda:");

        txtGoleoSegunda.setEditable(false);

        btnGuardar.setText("Cerrar Torneo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTorneo(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSubSegunda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addComponent(cboCampeonSegunda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(txtGoleoPrimera))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSubPrimera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCampeonPrimera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(txtGoleoSegunda))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboCampeonPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboSubPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboCampeonSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboSubSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGoleoPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGoleoSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarTorneo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTorneo
        int dialogResult = JOptionPane.showConfirmDialog(null, "Está seguro que desea cerrar el torneo?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (txtFechaFin.getText() == null || txtFechaFin.getText().trim().isEmpty()) {
                agregarMensajeAdvertencia("La fecha de fin es requerida");
                return;
            } else {
                try {
                    Date fechaFin = new SimpleDateFormat("dd/MM/yyyy").parse(txtFechaFin.getText());
                    torneo.setFechaFin(fechaFin);
                } catch (Exception ex) {
                    agregarMensajeAdvertencia("El formato de la fecha de inicio es incorrecto (dd/MM/yyyy)");
                    return;
                }
            }
            if (torneo.getFechaFin().before(torneo.getFechaInicio())) {
                agregarMensajeAdvertencia("La Fecha de Fin no puede ser menor a la Fecha de Inicio");
                return;
            }
            if (cboCampeonPrimera.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("Debe seleccionar el Campeón de Primera");
                return;
            } else {
                torneo.setCampeonPrimera(
                        Integer.parseInt(cboCampeonPrimera.getSelectedItem().toString().split(" - ")[0]));
            }
            if (cboSubPrimera.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("Debe seleccionar el Subcampeón de Primera");
                return;
            } else {
                torneo.setSubcampeonPrimera(
                        Integer.parseInt(cboSubPrimera.getSelectedItem().toString().split(" - ")[0]));
            }
            if (cboCampeonSegunda.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("Debe seleccionar el Campeón de Segunda");
                return;
            } else {
                torneo.setCampeonSegunda(
                        Integer.parseInt(cboCampeonSegunda.getSelectedItem().toString().split(" - ")[0]));
            }
            if (cboSubSegunda.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("Debe seleccionar el Subcampeón de Segunda");
                return;
            } else {
                torneo.setSubcampeonPrimera(
                        Integer.parseInt(cboSubSegunda.getSelectedItem().toString().split(" - ")[0]));
            }
            if (torneo.getCampeonPrimera().equals(torneo.getSubcampeonPrimera())) {
                agregarMensajeAdvertencia("El Campeón y Subcampeón de Primera no puede ser el mismo equipo");
                return;
            }
            if (torneo.getCampeonSegunda().equals(torneo.getSubcampeonSegunda())) {
                agregarMensajeAdvertencia("El Campeón y Subcampeón de Segunda no puede ser el mismo equipo");
                return;
            }
            try {
                torneoDAO.cerrarTorneo(torneo);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_cerrarTorneo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboCampeonPrimera;
    private javax.swing.JComboBox cboCampeonSegunda;
    private javax.swing.JComboBox cboSubPrimera;
    private javax.swing.JComboBox cboSubSegunda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtGoleoPrimera;
    private javax.swing.JTextField txtGoleoSegunda;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
