/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lmfvgo.vista;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import lmfvgo.db.ReglamentoDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.Reglamento;
import lmfvgo.util.ReportesManager;

/**
 *
 * @author cgarcia
 */
public class TorneoReglamentoVista extends FormBase {

    private final ReglamentoDAO reglamentoDAO;
    private final ReportesManager reportesManager;
    private boolean editar;
    /** Creates new form TorneoReglamentoVista */
    public TorneoReglamentoVista() {
        initComponents();
        reglamentoDAO = new ReglamentoDAO();
        reportesManager = new ReportesManager();
        editar = false;
        lblEditar.setVisible(false);
        List<Reglamento> reglas = reglamentoDAO.consultaPorFiltros(new Reglamento());
        if (reglas != null && !reglas.isEmpty()) {
            llenarResultado(reglas);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtJuegos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setClosable(true);
        setTitle("REGLAMENTO");

        jLabel1.setText("Clave:");

        jLabel2.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scrollPane.setViewportView(txtDescripcion);

        jLabel3.setText("Juegos:");

        jLabel4.setText("Multa:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        lblEditar.setForeground(new java.awt.Color(255, 0, 0));
        lblEditar.setText("EDITANDO...");

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Descripción", "Juegos", "Multa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarDetalle(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        btnReporte.setText("PDF");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(lblEditar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        txtClave.setText(null);
        txtClave.setEnabled(true);
        txtDescripcion.setText(null);
        txtJuegos.setText(null);
        txtMulta.setText(null);
        editar = false;
        lblEditar.setVisible(false);
        btnBuscar.setEnabled(true);
        limpiarTabla(tblResultado);
    }//GEN-LAST:event_limpiar

    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        Reglamento r = new Reglamento();
        if (!editar && (txtClave.getText() == null || txtClave.getText().isEmpty())) {
            agregarMensajeAdvertencia("La clave es requerida");
            return;
        } else {
            r.setClave(txtClave.getText());
        }
        if (txtDescripcion.getText() == null || txtDescripcion.getText().isEmpty()) {
            agregarMensajeAdvertencia("La descripcion es requerida");
        } else {
            r.setDescripcion(txtDescripcion.getText());
        }
        if (txtJuegos.getText() != null && !txtJuegos.getText().isEmpty()) {
            try {
                r.setSancionJuegos(Integer.parseInt(txtJuegos.getText()));
            } catch (NumberFormatException nfe) {
                agregarMensajeAdvertencia("El campo Juegos debe ser numérico");
                return;
            }
        }
        if (txtMulta.getText() != null && !txtMulta.getText().isEmpty()) {
            try {
                r.setSancionEconomica(Float.parseFloat(txtMulta.getText()));
            } catch (NumberFormatException nfe2) {
                agregarMensajeAdvertencia("El campo Multa debe ser numérico");
                return;
            }
        }
        if ((r.getSancionJuegos() == null || r.getSancionJuegos() == 0) &&
                (r.getSancionEconomica() == null || r.getSancionEconomica() == 0)) {
            agregarMensajeAdvertencia("Los juegos y/o multa son requeridos");
            return;
        }
        try {
            if (editar) {
                reglamentoDAO.actualizarReglamento(r);
                agregarMensajeExito("El reglamento fue actualizado correctamente");
            } else {
                reglamentoDAO.guardarReglamento(r);
                agregarMensajeExito("El reglamento fue guardado correctamente");
            }
            limpiar(evt);
        } catch (LMFVGOException ex) {
            agregarMensajeError(ex.getMessage());
        }
        
    }//GEN-LAST:event_guardar

    private void cargarDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarDetalle
        if (SwingUtilities.isRightMouseButton(evt)) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea editar el reglamento?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tblResultado.getModel();
                txtClave.setText(model.getValueAt(tblResultado.getSelectedRow(), 0).toString());
                txtClave.setEnabled(false);
                txtDescripcion.setText(model.getValueAt(tblResultado.getSelectedRow(), 1).toString());
                txtJuegos.setText(model.getValueAt(tblResultado.getSelectedRow(), 2) != null ? 
                        model.getValueAt(tblResultado.getSelectedRow(), 2).toString() : null);
                txtMulta.setText(model.getValueAt(tblResultado.getSelectedRow(), 3) != null ?
                        model.getValueAt(tblResultado.getSelectedRow(), 3).toString() : null);
                lblEditar.setVisible(true);
                editar = true;
                btnBuscar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cargarDetalle

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        limpiarTabla(tblResultado);
        Reglamento r = new Reglamento();
        if (txtClave.getText() != null && !txtClave.getText().isEmpty()) {
            r.setClave(txtClave.getText());
        }
        if (txtDescripcion.getText() != null && !txtDescripcion.getText().isEmpty()) {
            r.setDescripcion(txtDescripcion.getText());
        }
        if (txtJuegos.getText() != null && !txtJuegos.getText().isEmpty()) {
            try {
                r.setSancionJuegos(Integer.parseInt(txtJuegos.getText()));
            } catch (NumberFormatException ex) {
                agregarMensajeAdvertencia("El campo Juegos debe ser numérico");
                return;
            }
        }
        if (txtMulta.getText() != null && !txtMulta.getText().isEmpty()) {
            try {
                r.setSancionEconomica(Float.parseFloat(txtMulta.getText()));
            } catch (NumberFormatException ex) {
                agregarMensajeAdvertencia("El campo Multa debe ser numérico");
                return;
            }
        }
        List<Reglamento> reglas = reglamentoDAO.consultaPorFiltros(r);
        if (reglas != null && !reglas.isEmpty()) {
            llenarResultado(reglas);
        } else {
            agregarMensajeAdvertencia("No se encontraron resultados");
        }
    }//GEN-LAST:event_buscar

    private void reporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte
        List<Reglamento> reglas = reglamentoDAO.consultaPorFiltros(new Reglamento());
        if (reglas != null && !reglas.isEmpty()) {
            try {
                reportesManager.reglamento(reglas);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        } else {
            agregarMensajeError("No existe el reglamento");
        }
    }//GEN-LAST:event_reporte

    private void llenarResultado(List<Reglamento> reglas) {
        DefaultTableModel modelo = (DefaultTableModel) tblResultado.getModel();
            for (Reglamento rg : reglas) {
                modelo.addRow(new Object[]{rg.getClave(), rg.getDescripcion(),
                        (rg.getSancionJuegos() != null && rg.getSancionJuegos() > 0 ? rg.getSancionJuegos() : null),
                        (rg.getSancionEconomica() != null && rg.getSancionEconomica() > 0 ? rg.getSancionEconomica() : null)});
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtJuegos;
    private javax.swing.JTextField txtMulta;
    // End of variables declaration//GEN-END:variables

}
