/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lmfvgo.vista;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import lmfvgo.db.EquiposDAO;
import lmfvgo.db.EstadisticasEquipoDAO;
import lmfvgo.db.TorneoDAO;
import lmfvgo.excepciones.LMFVGOException;
import lmfvgo.modelo.EquipoLiguilla;
import lmfvgo.modelo.EstadisticasJugador;
import lmfvgo.modelo.Torneo;

/**
 *
 * @author USUARIO
 */
public class TorneoCierreVista extends FormBase {
    private static final long serialVersionUID = 1083223223522493168L;
    
    private final TorneoDAO torneoDAO;
    private final EstadisticasEquipoDAO estadisticasEquipoDAO;
    private final EquiposDAO equiposDAO;
    private Torneo torneo;

    /**
     * Creates new form TorneoCierreVista
     * @param con
     */
    public TorneoCierreVista(Connection con) {
        initComponents();
        torneoDAO = new TorneoDAO(con);
        equiposDAO = new EquiposDAO(con);
        estadisticasEquipoDAO = new EstadisticasEquipoDAO(con);
        
        torneo = torneoDAO.torneoActivo();
        
        txtNombre.setText(torneo.getNombre());
        
        List<EstadisticasJugador> goleo1 = estadisticasEquipoDAO.consultaGoleo(1);
        List<EstadisticasJugador> goleo2 = estadisticasEquipoDAO.consultaGoleo(2);
        
        List<EquipoLiguilla> equiposPrimera = equiposDAO.consultaCampeonSub(1);
        
        List<EquipoLiguilla> equiposSegunda = equiposDAO.consultaCampeonSub(2);
        
        for (EquipoLiguilla eq1 : equiposPrimera) {
            if (!eq1.isEliminado()) {
                txtCampeon1.setText(eq1.getIdEquipo() + " - " + eq1.getNombre());
                
            } else {
                txtSub1.setText(eq1.getIdEquipo() + " - " + eq1.getNombre());
            }
        }
        
        for (EquipoLiguilla eq2 : equiposSegunda) {
            if (!eq2.isEliminado()) {
                txtCampeon2.setText(eq2.getIdEquipo() + " - " + eq2.getNombre());
            } else {
                txtSub2.setText(eq2.getIdEquipo() + " - " + eq2.getNombre());
            }
        }
        
        if (goleo1 != null && !goleo1.isEmpty()) {
            txtGoleoPrimera.setText(goleo1.get(0).getNombreJugador());
            torneo.setGoleadorPrimera(goleo1.get(0).getIdJugador());
        }
        if (goleo2 != null && !goleo2.isEmpty()) {
            txtGoleoSegunda.setText(goleo2.get(0).getNombreJugador());
            torneo.setGoleadorSegunda(goleo2.get(0).getIdJugador());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGoleoPrimera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGoleoSegunda = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtCampeon1 = new javax.swing.JTextField();
        txtCampeon2 = new javax.swing.JTextField();
        txtSub1 = new javax.swing.JTextField();
        txtSub2 = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Nombre:");

        txtNombre.setEditable(false);

        jLabel2.setText("Fecha Fin:");

        jLabel3.setText("Campeón Primera:");

        jLabel4.setText("Subcampeón Primera:");

        jLabel5.setText("Campeón Segunda:");

        jLabel6.setText("Subcampeón Segunda:");

        jLabel7.setText("Goleo Primera:");

        txtGoleoPrimera.setEditable(false);

        jLabel8.setText("Goleo Segunda:");

        txtGoleoSegunda.setEditable(false);

        btnGuardar.setText("Cerrar Torneo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTorneo(evt);
            }
        });

        txtCampeon1.setEditable(false);

        txtCampeon2.setEditable(false);

        txtSub1.setEditable(false);

        txtSub2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGoleoSegunda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGoleoPrimera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSub2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCampeon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSub1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCampeon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCampeon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCampeon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGoleoPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGoleoSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarTorneo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTorneo
        int dialogResult = JOptionPane.showConfirmDialog(null, "Está seguro que desea cerrar el torneo?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (txtFechaFin.getText() == null || txtFechaFin.getText().trim().isEmpty()) {
                agregarMensajeAdvertencia("La fecha de fin es requerida");
                return;
            } else {
                try {
                    Date fechaFin = new SimpleDateFormat("dd/MM/yyyy").parse(txtFechaFin.getText());
                    torneo.setFechaFin(fechaFin);
                } catch (Exception ex) {
                    agregarMensajeAdvertencia("El formato de la fecha de inicio es incorrecto (dd/MM/yyyy)");
                    return;
                }
            }
            if (torneo.getFechaFin().before(torneo.getFechaInicio())) {
                agregarMensajeAdvertencia("La Fecha de Fin no puede ser menor a la Fecha de Inicio");
                return;
            }
            if (txtCampeon1.getText() == null || txtCampeon1.getText().isEmpty()) {
                agregarMensajeAdvertencia("Debe seleccionar el Campeón de Primera");
                return;
            } else {
                torneo.setCampeonPrimera(
                        Integer.parseInt(txtCampeon1.getText().split(" - ")[0]));
            }
            if (txtSub1.getText() == null || txtSub1.getText().isEmpty()) {
                agregarMensajeAdvertencia("Debe seleccionar el Subcampeón de Primera");
                return;
            } else {
                torneo.setSubcampeonPrimera(
                        Integer.parseInt(txtSub1.getText().split(" - ")[0]));
            }
            if (txtCampeon2.getText() == null || txtCampeon2.getText().isEmpty()) {
                agregarMensajeAdvertencia("Debe seleccionar el Campeón de Segunda");
                return;
            } else {
                torneo.setCampeonSegunda(
                        Integer.parseInt(txtCampeon2.getText().split(" - ")[0]));
            }
            if (txtSub2.getText() == null || txtSub2.getText().isEmpty()) {
                agregarMensajeAdvertencia("Debe seleccionar el Subcampeón de Segunda");
                return;
            } else {
                torneo.setSubcampeonPrimera(
                        Integer.parseInt(txtSub2.getText().split(" - ")[0]));
            }
            if (torneo.getCampeonPrimera().equals(torneo.getSubcampeonPrimera())) {
                agregarMensajeAdvertencia("El Campeón y Subcampeón de Primera no puede ser el mismo equipo");
                return;
            }
            if (torneo.getCampeonSegunda().equals(torneo.getSubcampeonSegunda())) {
                agregarMensajeAdvertencia("El Campeón y Subcampeón de Segunda no puede ser el mismo equipo");
                return;
            }
            try {
                torneoDAO.cerrarTorneo(torneo);
            } catch (LMFVGOException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_cerrarTorneo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCampeon1;
    private javax.swing.JTextField txtCampeon2;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtGoleoPrimera;
    private javax.swing.JTextField txtGoleoSegunda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSub1;
    private javax.swing.JTextField txtSub2;
    // End of variables declaration//GEN-END:variables
}
