/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lmfvgo.vista;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import lmfvgo.db.TorneoDAO;
import lmfvgo.excepciones.LMFVGOException;

/**
 *
 * @author cgarcia
 */
public class TorneoRegistroVista extends FormBase {

    private final TorneoDAO torneoDAO;
    /** Creates new form TorneoRegistroVista */
    public TorneoRegistroVista() {
        initComponents();
        torneoDAO = new TorneoDAO();
        txtFechaInicio.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nuevo Torneo");

        jLabel1.setText("Nombre");

        jLabel2.setText("Inicio");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTorneo(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTorneo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTorneo
        Date fechaInicio = null;
        if (txtNombre.getText() == null || txtNombre.getText().trim().isEmpty()) {
            agregarMensajeAdvertencia("El nombre del torneo es requerido");
            return;
        }
        if (txtFechaInicio.getText() == null || txtFechaInicio.getText().trim().isEmpty()) {
            agregarMensajeAdvertencia("La fecha de inicio es requerido");
            return;
        } else {
            try {
                fechaInicio = new SimpleDateFormat("dd/MM/yyyy").parse(txtFechaInicio.getText());
            } catch (Exception ex) {
                agregarMensajeAdvertencia("El formato de la fecha de inicio es incorrecto (dd/MM/yyyy)");
                return;
            }
        }
        try {
            Map<String, Object> mapa = torneoDAO.torneoActivo();
            if (mapa == null) {
                torneoDAO.guardarTorneo(txtNombre.getText(), fechaInicio);
                agregarMensajeExito("El torneo fue registrado correctamente");
            } else {
                agregarMensajeError("Ya existe un torneo activo");
            }
        } catch (LMFVGOException ex){
            agregarMensajeError(ex.getMessage());
        }
        
    }//GEN-LAST:event_guardarTorneo


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
